name: wifi_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar: ^1.12.30
  cubit_form: ^2.0.5
  cupertino_icons: ^1.0.8
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LatoRegular
      fonts:
        - asset: assets/font/Lato-Regular.ttf
    - family: LatoBold
      fonts:
        - asset: assets/font/Lato-Bold.ttf
